import { afterAll, beforeEach, describe, expect, it } from "vitest";
import { prisma } from "@perflo-ap-agent/db";
import { encryptPaymentMethod, hashPaymentMethod, normalizePaymentMethod } from "./payee-crypto.js";
import { loadApprovedPayees } from "./payee-store.js";

const encryptionKey = "c".repeat(64);
const hashKey = "d".repeat(64);
const ids = ["test-payee-store-1", "test-payee-store-2"];

// Prisma's generated BYTEA input uses Uint8Array; copy the crypto Buffer so
// its backing buffer is the exact ArrayBuffer type Prisma declares.
const prismaBytes = (value: Buffer): Uint8Array<ArrayBuffer> => {
  const copy = new Uint8Array(new ArrayBuffer(value.length));
  copy.set(value);
  return copy;
};

async function cleanup() {
  await prisma.payeeIdentity.deleteMany({ where: { payeeId: { in: ids } } });
  await prisma.payeePaymentMethod.deleteMany({ where: { payeeId: { in: ids } } });
  await prisma.payee.deleteMany({ where: { id: { in: ids } } });
}

beforeEach(async () => {
  process.env.PAYEE_ENCRYPTION_KEY = encryptionKey;
  process.env.PAYEE_HASH_KEY = hashKey;
  await cleanup();
});

afterAll(async () => {
  await cleanup();
});

describe("Payee store — real Postgres encrypted-rail integration", () => {
  it("loads an approved identity only by decrypting its stored encrypted rail in worker memory", async () => {
    const normalized = normalizePaymentMethod({ kind: "upi", vpa: "Riya@OKAXIS" });
    await prisma.payee.create({
      data: {
        id: ids[0], name: "Riya", recipientNickname: "riya-perflo", grantApproved: true,
        identities: { create: { senderAddr: "billing@riya.example" } },
        paymentMethods: { create: { rail: "upi", encryptedPayload: prismaBytes(encryptPaymentMethod(normalized)), lookupHash: hashPaymentMethod(normalized) } },
      },
    });
    await prisma.payee.create({
      data: {
        id: ids[1], name: "Unapproved", recipientNickname: "unapproved-perflo", grantApproved: false,
        identities: { create: { senderAddr: "billing@unapproved.example" } },
        paymentMethods: { create: { rail: "upi", encryptedPayload: prismaBytes(encryptPaymentMethod("upi:unapproved@okaxis")), lookupHash: hashPaymentMethod("upi:unapproved@okaxis") } },
      },
    });

    const loaded = await loadApprovedPayees();
    expect(loaded).toContainEqual({
      payeeId: ids[0], senderAddr: "billing@riya.example", recipientNickname: "riya-perflo",
      paymentMethod: { kind: "upi", vpa: "riya@okaxis" },
    });
    expect(loaded).not.toEqual(expect.arrayContaining([expect.objectContaining({ payeeId: ids[1] })]));

    const stored = await prisma.payeePaymentMethod.findFirstOrThrow({ where: { payeeId: ids[0] } });
    expect(Buffer.from(stored.encryptedPayload).toString("utf8")).not.toContain("riya@okaxis");
  });

  it("excludes a revoked rail from resolver lookup even though the payee is still approved", async () => {
    const normalized = normalizePaymentMethod({ kind: "upi", vpa: "riya@okaxis" });
    await prisma.payee.create({
      data: {
        id: ids[0], name: "Riya", recipientNickname: "riya-perflo", grantApproved: true,
        identities: { create: { senderAddr: "billing@riya.example" } },
        paymentMethods: {
          create: {
            rail: "upi",
            encryptedPayload: prismaBytes(encryptPaymentMethod(normalized)),
            lookupHash: hashPaymentMethod(normalized),
            status: "revoked",
            revokedAt: new Date(),
          },
        },
      },
    });

    const loaded = await loadApprovedPayees();
    expect(loaded).not.toEqual(expect.arrayContaining([expect.objectContaining({ payeeId: ids[0] })]));
  });

  it("lets Postgres enforce the global unique lookup-hash constraint", async () => {
    const normalized = normalizePaymentMethod({ kind: "upi", vpa: "riya@okaxis" });
    const encrypted = encryptPaymentMethod(normalized);
    const hash = hashPaymentMethod(normalized);
    for (const id of ids) {
      await prisma.payee.create({ data: { id, name: id, recipientNickname: id } });
    }
    await prisma.payeePaymentMethod.create({ data: { payeeId: ids[0], rail: "upi", encryptedPayload: prismaBytes(encrypted), lookupHash: hash } });
    await expect(prisma.payeePaymentMethod.create({
      data: { payeeId: ids[1], rail: "upi", encryptedPayload: prismaBytes(encrypted), lookupHash: hash },
    })).rejects.toMatchObject({ code: "P2002" });
  });
});
